# Generated by Django 2.2 on 2019-04-10 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funcionario', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Funcionario',
            new_name='Usuario',
        ),
    ]
