# Generated by Django 2.2 on 2019-04-10 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funcionario', '0002_auto_20190410_0122'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuario',
            new_name='Funcionario',
        ),
    ]
