# Generated by Django 2.2 on 2019-04-10 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionario', '0003_auto_20190410_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='date_aso',
            field=models.DateField(),
        ),
    ]
