# Generated by Django 2.2 on 2019-04-10 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funcionario', '0005_auto_20190410_0135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='data_de_Admissao',
        ),
    ]
