# Generated by Django 2.2 on 2019-04-10 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funcionario', '0006_remove_funcionario_data_de_admissao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_primeiro', models.DateTimeField()),
                ('data_proximo', models.DateTimeField()),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funcionario.Funcionario')),
            ],
        ),
    ]
